# This workflow will build and submit dependency tree, it needs write permission and thus cannot be triggered by pull requests 

name: Build and Test

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate and submit dependency tree
      uses: gradle/gradle-build-action@v2.9.0
      with:
        dependency-graph: generate-and-submit
        arguments: build
        
